apiVersion: v1
kind: Service
metadata:
  name: b-shippingservice
spec:
  ports:
    - name: c-http
      port: 50051
      targetPort: 50051
      protocol: TCP
  selector:
    app.kubernetes.io/name: b-shippingservice
  type: LoadBalancer
